server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: http://localhost:8082
          predicates:
            - Path=/employees/**
        - id: department-service
          uri: http://localhost:8081
          predicates:
            - Path=/departments/**
      
  application:
    name: api-gateway

  config:
    import: "optional:configserver:http://localhost:8088"

  main:
    web-application-type: reactive

